### PR TITLE
Who Doesn't like Features?

### PR DESCRIPTION
**Pull request by Agent24015**

### CODE REVIEW

**Review by heisinbug — COMMENTED** [review]
can u share ss after enabling this overlay and before this overlays ?

**Comment by Agent24015** [comment]
Yes sure,

Screenshot_20210115-163628_Settings
Screenshot_20210115-163952_Settings
Screenshot_20210115-165525_Settings
Screenshot_20210115-165455_Device_Personalization_Services
Screenshot_20210115-163551_Settings

As you can see, the option for memory is available for each app in settings & adaptive sound is also there.

**Comment by Agent24015** [comment]
This is the SS before enabling memory overlay if you need it 

Screenshot_20210116-135335_Settings

**Comment by heisinbug** [comment]
Can u contact me on tg (@heisinbug)

**Comment by Agent24015** [comment]
> Can u contact me on tg (@heisinbug)

Ok 👍

**Pull request merged**
